spring:
  application:
  name: butler

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: qorwhdgus!!100

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

